"""
The review-processing job.

This is the function the worker runs for each queued job. It is a plain
module-level function (not a method) because rq serializes the reference
by import path — the worker process must be able to import it.

The job manages its OWN database session — it runs in a separate process
and cannot reuse the web request's session.
"""
import asyncio
from datetime import datetime, timezone

from app.core.database import SessionLocal
from app.core.github_client import GitHubClient
from app.core.reviewer import review_diff
from app.models.models import (
    Review,
    Repository,
    User,
    ReviewStatus,
    ReviewComment,
    Severity,
)

_SEVERITY_LABEL = {
    "critical": "Critical",
    "error": "Error",
    "warning": "Warning",
    "info": "Info",
}


def _format_summary(findings: list[dict], pr_number: int) -> str:
    """Render the findings into a Markdown summary comment for the PR."""
    if not findings:
        return (
            "## Automated Code Review\n\n"
            "No issues found. Nice work!"
        )

    lines = [
        "##  Automated Code Review",
        "",
        f"Found {len(findings)} item(s) worth a look:",
        "",
    ]
    for f in findings:
        label = _SEVERITY_LABEL.get(f["severity"], f["severity"])
        loc = f["file_path"]
        if f.get("line_number"):
            loc += f":{f['line_number']}"
        lines.append(f"- **{label}** — `{loc}`  \n  {f['body']}")
    lines.append("")
    lines.append("_Generated by CodeReviewBot._")
    return "\n".join(lines)


def process_review(review_id: str) -> dict:
    """Entry point invoked by the rq worker for each job."""
    db = SessionLocal()
    try:
        review = db.query(Review).filter(Review.id == review_id).first()
        if not review:
            return {"status": "error", "reason": f"Review {review_id} not found"}

        # Claim the review up front so its status is visible while the job runs
        review.status = ReviewStatus.IN_PROGRESS
        db.commit()

        # Resolve repo + owner token
        repo = db.query(Repository).filter(Repository.id == review.repository_id).first()
        owner = db.query(User).filter(User.id == repo.owner_id).first() if repo else None
        token = owner.access_token if owner else None

        gh = GitHubClient(access_token=token)

        # 1. Fetch the diff from GitHub
        try:
            # get_pr_diff is async but rq runs jobs synchronously
            diff = asyncio.run(gh.get_pr_diff(repo.full_name, review.pr_number))
            review.diff_text = diff
            db.commit()
        except Exception as e:
            # Commit the failure so the review isn't left stuck in progress
            review.status = ReviewStatus.FAILED
            db.commit()
            return {"status": "failed", "reason": f"diff fetch failed: {e}"}

        # 2. Ask Claude to review it
        try:
            findings = review_diff(review.diff_text)
        except Exception as e:
            review.status = ReviewStatus.FAILED
            db.commit()
            return {"status": "failed", "reason": f"Claude analysis failed: {e}"}

        # 3. Persist each finding as a ReviewComment row
        for f in findings:
            comment = ReviewComment(
                review_id=review.id,
                file_path=f["file_path"],
                line_number=f["line_number"],
                severity=Severity(f["severity"]),
                body=f["body"],
            )
            db.add(comment)
        db.commit()

        # 4. Post a summary back to the PR. Best-effort: a delivery problem
        #    shouldn't discard a review we already paid for and stored.
        posted = False
        try:
            summary = _format_summary(findings, review.pr_number)
            asyncio.run(
                gh.post_issue_comment(repo.full_name, review.pr_number, summary)
            )
            for c in review.comments:
                c.posted_to_github = True
            posted = True
            db.commit()
        except Exception:
            posted = False

        review.status = ReviewStatus.COMPLETED
        review.completed_at = datetime.now(timezone.utc)
        db.commit()

        return {
            "status": "completed",
            "review_id": review_id,
            "diff_bytes": len(review.diff_text or ""),
            "findings": len(findings),
            "posted_to_github": posted,
        }
    finally:
        # finally, so the session closes on every path including the early returns
        db.close()